export const POST_COMPLETION_ITEMS = [
  "Electricity — set up account (note MPRN from meter)",
  "Gas — set up account (note GPRN from meter)",
  "Broadband — order 2-3 weeks before closing",
  "Bin collection — sign up (Panda/Greenstar/CityBin)",
  "An Post mail redirection (anpost.com, €35/month)",
  "Uisce Éireann — register water meter",
  "Home alarm — set up monitoring, change codes",
  "Local Property Tax — register with Revenue",
  "Home insurance — confirm policy active",
  "Mortgage protection — confirm active",
  "Change of address: bank",
  "Change of address: employer",
  "Change of address: Revenue",
  "Change of address: GP and dentist",
  "Change of address: car insurance and registration",
  "TV licence — register at anpost.com",
  "Electoral register — checktheregister.ie",
  "Meter readings — photograph all meters on key day",
  "Stopcock — find and test water shutoff",
  "Fuse board — label all circuits",
  "Boiler — schedule first service",
  "Locks — consider changing external locks",
];
