// Default snag items grouped by room for new builds
export const DEFAULT_SNAG_ITEMS: { room: string; items: string[] }[] = [
  { room: "Kitchen", items: ["Worktop joints and edges", "Cabinet doors aligned and closing", "Drawer runners smooth", "Splashback sealed", "Sink and taps — no leaks", "Appliances working", "Extractor fan working", "Socket and switch plates flush", "Tiles — no cracks or lippage", "Flooring — no damage or gaps"] },
  { room: "Bathroom", items: ["Toilet flush and fill", "Shower pressure and drainage", "Bath — no chips, sealant intact", "Tiles grouted and sealed", "Extractor fan working", "Mirror and cabinet secure", "Towel rail/radiator heating", "No leaks under sink", "Flooring sealed at edges"] },
  { room: "Bedrooms", items: ["Doors open/close smoothly", "Window locks and handles", "Radiator heating evenly", "Sockets and switches working", "Wardrobe doors aligned", "Paintwork — no marks or runs", "Skirting boards — no gaps", "Flooring — no damage"] },
  { room: "Living Areas", items: ["Fireplace/stove draws correctly", "Doors and handles", "Windows — seals intact, no draughts", "Radiators heating evenly", "Light fittings secure", "Paintwork consistent", "Skirting and architrave — gaps", "Flooring level and undamaged"] },
  { room: "Hallway/Stairs", items: ["Front door — locks, seal, draught", "Staircase — solid, no creaks", "Handrail secure", "Under-stairs storage door", "Smoke alarm working", "Carbon monoxide alarm", "Doorbell working", "Meter cupboard accessible"] },
  { room: "Attic", items: ["Insulation installed correctly", "No gaps at eaves", "Water tank lagged", "Ventilation adequate", "Fire stops at party wall", "Truss clips in place", "Roof felt intact — no daylight visible", "Attic hatch — insulated and sealed"] },
  { room: "Exterior", items: ["Roof tiles/slates — none missing", "Gutters and downpipes — aligned, no leaks", "Fascia and soffit — no gaps", "External walls — render/brick intact", "Window sills — sealed, drip edge", "Front door threshold sealed", "Driveway — no cracks or settlement", "Garden — topsoil and drainage", "Boundary walls/fences complete", "External tap working", "Outside lights working", "Meter box accessible"] },
  { room: "Utilities", items: ["Boiler firing and heating water", "Hot water at all taps", "Fuse board labelled", "All circuits working", "Water stopcock accessible and working", "Gas meter accessible", "Broadband conduit in place", "Alarm system operational"] },
];
